README.md
- Add link to use Gitpod for contribution
=> docs: add link to contribute through gitpod

src/components/Footer.js
Update Footer text to "Contribute to Focusly" with a link to the repository.
=> Update Footer #12

src/components/Tabs.js
#14 
Changed the Links of the Tabs to Navlinks, so page wont be reloaded after clicking
=> Changed the links to Navlinks

README.md
Added Contribution Guidelines
Closes: #4 
Added Contribution Guidelines
- [X ] This change requires a documentation update
NULL
- [ X] I have made corresponding changes to the documentation.
Original Screenshot | Updated Screenshot |
=> Added Contribution Guidelines

.github/ISSUE_TEMPLATE/bug_report.md
Also fixing any markdown lint violations so it's cleaner for the next person to read
Closes: #issue number that will be closed through this PR
Give a clear description what modifications you have made
Just making it so that there is not 2 screenshot sections, but 1
Original Screenshot | Updated Screenshot |
=> Fix the bug report Issue Template #29

src/components/Footer.js
Closes: #issue number that will be closed through this PR
This is will fix issue #34 
Added the same container to the footer as the homepage
- [ x] Bug fix (non-breaking change which fixes an issue)
Viewed the app in the browser to verify the solution works
- [x ] My code follows the guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly wherever it was hard to understand.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [x ] I have added tests that prove my fix is effective or that my feature works.
- [x ] Any dependent changes have been merged and published in downstream modules. …
=> Added the same container from the header to footer

package-lock.json, src/App.js, src/components/Footer.js
Closes: #33 
The navbar was not showing in the completly because there was a padding in Container component and the nav was nested within the container so when i changed the padding of container to zero it displayed correctly
- [] New feature (non-breaking change which adds functionality)
manually
| ![image](https://user-images.githubusercontent.com/38073631/185778056-2a15aade-6da5-4dcd-b974-262612b81186.png) |
=> fix navbar width issue

public/index.html
Adding Analytics to Focusly using Splitbee
=> Adding analytics

src/components/Card.js, src/components/Navbar.js, src/components/Stopwatch/useTimer.js
Closes: #22
Adde Link to the Navbar
=> Link Added to Navbar

package-lock.json, src/components/Tabs.js
Closes: #49 
Changed the label of the first tab in `Tabs.js` from Focus to Work.
=> Change focus mode name to work in tab

package-lock.json, src/components/Navbar.js
Closes: #issue number that will be closed through this PR
Give a clear description what modifications you have made
Original Screenshot | Updated Screenshot |
=> Make the Navbar fixed #53

public/index.html, src/components/Meditate.js, src/components/Navbar.js, src/components/Tabs.js
Closes: #57 
Give a clear description what modifications you have made
Added Tabs in Navbar
=> Tabs added in Navbar

public/index.html
Closes #64 .
Upgraded analytics to beam analytics.
=> analytics upgraded

src/components/Footer.js, src/components/Navbar.js
Closes: #67 
Added Top and Bottom border to navbar and footer.
|
=> navbar and footer improve

package-lock.json, src/components/Footer.js
Closes: #84  number that will be closed through this PR
Changed footer text alignment in order to make it look better
|   Original    | Updated  |
| ------------- | ------------- |
| ![Screenshot_7](https://github.com/Utkarshn10/Focusly/assets/128291891/d03eef0e-0d9c-4c70-ba0d-59fe6601ea3f)  |  (Large Screens) ![Screenshot_8](https://github.com/Utkarshn10/Focusly/assets/128291891/3535cb68-9035-4633-a2be-59c7b5d98b8e) (Medium Screens) ![Screenshot_9](https://github.com/Utkarshn10/Focusly/assets/128291891/f2c77a85-cfa8-4e3b-8232-543c8130535b) ![Screenshot_10](https://github.com/Utkarshn10/Focusly/assets/128291891/a0a20638-17bd-42ff-bad1-fd96223990e6) (Phones)
=> fix: fixed footer text alignment

package-lock.json, src/components/Card.js
Closes: #73 number that will be closed through this PR
Changed footer text alignment in order to make it look better
|   Original    | Updated  |
| ------------- | ------------- |
| ![Screenshot_2](https://github.com/Utkarshn10/Focusly/assets/128291891/7da639ae-a145-4fcf-8470-3d1ded73cd28)  |  https://github.com/Utkarshn10/Focusly/assets/128291891/b45a7732-c0e8-4a37-a03a-1641055b529f  (Video example)                            ![Screenshot_3](https://github.com/Utkarshn10/Focusly/assets/128291891/58dd899e-77a3-43a8-913e-27dc6721b0b8)
=> feature: added share button

src/components/Card.js
Fixed Timer speeding up with increase in number of cards selected. Closes #92
=> fix: Timer

src/components/Footer.js
Closes: #96
- Changed Base start of the footer's templateColumn to templateRow and moved the templateColumn to happen after md screens w/ ChakraUI syntax.
- [x ] Bug fix (non-breaking change which fixes an issue)
- Testing with Dev Tools of Browser with multiple screen sizes.
- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
=> Fix Footer in mobile view #96 Resolved

src/components/Tabs.js
Closes: Tabs fixes #99
Closes: #99
I have changed the click functionality to button.
I have tested it by clicking on all the buttons.
=> fix(app): Tabs fixes #99 Fixed the Navlink buttons

src/components/Homepage.js
Closes: #114 
Changed the Height and the Width of Shuffle button from `25px` to `30px`
Ran an NPM server locally and modified the changes real-time
Screenshot of the changes made:
=> Fixed the size proportions of Shuffle Button

.devcontainer/devcontainer.json
Closes: #127 
Add Devcontainer,json that will automatically configured the repo in the codespaces 
- [] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the guidelines of this project.
=> feat add devcontainer for codespaces

src/components/Footer.js
Closes: #134 
I have added the copyrights info to the footer
| Previous desktop version | previous mobile version | current desktop version | current mobile version |
| ------- | ------- | ------- | ------- |
| ![Image 1](https://github.com/Utkarshn10/Focusly/assets/130981122/c4977a76-5684-40e0-8747-5acf25aa80ee) | ![Image 2](https://github.com/Utkarshn10/Focusly/assets/130981122/107e4fed-de8c-43a5-9c1d-df3e13e72857) | ![Image 3](https://github.com/Utkarshn10/Focusly/assets/130981122/ef22edc8-96ff-469d-8508-7ff3636a0e57) | ![Image 4](https://github.com/Utkarshn10/Focusly/assets/130981122/c400e3f0-04c7-475b-a494-2e70842a032c) |
=> feat: footer added
